import localFont from "next/font/local";
import "./globals.css";
import { FormProvider } from "@/context/FormContext"; // ← FormProvider を追加

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <FormProvider> {/* ここで FormProvider をラップ */}
          {children}
        </FormProvider>
      </body>
    </html>
  );
}