import localFont from "next/font/local";
import "./globals.css";
import { FormProvider } from "@/context/FormContext"; // FormProvider を追加
import Header from "@/components/Header"; // ヘッダーをインポート

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <FormProvider> {/* FormProvider でラップ */}
          <Header /> {/* 追加: ヘッダーを組み込み */}
          <main className="p-4">{children}</main> {/* main タグを追加 */}
        </FormProvider>
      </body>
    </html>
  );
}